name: CI for Static Website

on:
  push:
    branches:
       -main
  pull_request:
    branches:
      -main

jobs:
  validate:
    name: Validate HTML & CSS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # VALIDATES HTML
      - name: Validate HTML
        uses: Cyb3r-jak3/html5-validator-action@v1.5.0
        with:
          file: "index.html"

      # VALIDATES CSS
      - name: Validate CSS
        uses: dkhunt27//css-validator-github-action@v1
        with:
          css_file: "style.css"

  deploy:
    name: Deploy to Github Pages
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: upload files
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./

      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v1    
